dataset_model:
  name: coco_tree_mask_rcnn_R_50_FPN_3x
  model:
    config_url: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
    num_workers: 2
    ims_per_batch: 2
    lr: !!float 0.0005
    max_iter: 20
    batch_size_per_im: 128
    num_classes: 1  # only 1 class (tree)
  train:
    option: No
    train_dataset_dir: datasets/coco_tree/training
    show_images: 3  # 0: don't show, change to an int as the number of images to show
  validation:
    option: No
    val_dataset_dir: datasets/coco_tree/validation
    use_pretrained_weight: Yes
    pretrained_weight: weights/coco_tree_mask_rcnn.pth
    show_images: 3  # 0: don't show, -1: show all, an int: number of ims to show
  test:
    option: Yes
    test_dataset_dir: datasets/coco_tree/testing/output_3d_consecutive/left_ims
    map_3d_points: Yes
    points_3d_path: datasets/coco_tree/testing/output_3d_consecutive/points_3d
    use_pretrained_weight: Yes
    pretrained_weight: weights/coco_tree_mask_rcnn.pth
    threshold: 0.5
    testing_device: cuda  # use cpu or cuda
    saving_predicted_ims: Yes
    show_predicted_ims: No


