dataset_model:
  name: coco_tree_mask_rcnn_R_50_FPN_3x
  train:
    option: No
    train_dataset_dir: datasets/coco_tree/training_subset
    show_images: 0  # 0: don't show, change to an int as the number of images to show
  validation:
    option: Yes
    val_dataset_dir: datasets/coco_tree/validation
    show_images: 3  # 0: don't show, -1: show all, an int: number of ims to show
  test:
    option: No
    test_dataset_dir: datasets/coco_tree/testing
    use_pretrained_weight: No
    pretrained_weight:
    threshold: 0.5
    testing_device: cuda  # use cpu or cuda
    saving_predicted_ims: Yes
    show_predicted_ims: Yes
  model:
    config_url: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
    num_workers: 2
    ims_per_batch: 2
    lr: !!float 0.00025
    max_iter: 100
    batch_size_per_im: 128
    num_classes: 1  # only 1 class (tree)
