dataset_model:
  name: coco_tree_mask_rcnn_R_50_FPN_3x
  train:
    option: No
    train_dataset_dir: datasets/coco_tree/training_subset
  validation:
    option: No
    val_dataset_dir:
  test:
    option: Yes
    test_dataset_dir: datasets/coco_tree/testing
    pretrained_weight: weights/coco_tree_mask_rcnn_R_50_FPN_3x_2000ims_3000epochs.pth
    threshold: 0.4
    testing_device: cuda  # use cpu or cuda
    saving_predicted_ims: Yes
  show_images: 3  # 0: don't show, change to an int as the number of images to show
  model:
    config_url: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
    num_workers: 2
    ims_per_batch: 2
    lr: !!float 0.00025
    max_iter: 100
    batch_size_per_im: 128
    num_classes: 1  # only 1 class (tree)
