dataset_model:
  name: coco_tree_retinanet_R_101_FPN_3x
  model:
    config_url: COCO-Detection/retinanet_R_101_FPN_3x.yaml  # https://bit.ly/36kvp9E
    num_workers: 2
    ims_per_batch: 2
    lr: !!float 0.0005
    max_iter: 2000
    batch_size_per_im: 128
    num_classes: 1  # only 1 class (tree)
  train:
    option: No
    train_dataset_dir: datasets/coco_tree_tank/training
    show_images: 0  # 0: don't show, change to an int as the number of images to show
  validation:
    option: Yes
    val_dataset_dir: datasets/coco_tree_tank/validation
    use_pretrained_weight: Yes
    pretrained_weight: weights/Nov17_trainRetinanet_R_101_FPN_3x_2000ims_lr0.0005.pth
    show_images: 0  # 0: don't show, -1: show all, an int: number of ims to show
  test:
    option: Yes
    test_dataset_dir: datasets/coco_tree_tank/testing/output_3d_reconstruction/left_ims
    map_3d_points: Yes
    remove_inf_points_mode:  # nothing or '1nn'
    points_3d_path: datasets/coco_tree_tank/testing/output_3d_reconstruction/points_3d
    use_pretrained_weight: Yes
    pretrained_weight: weights/Nov17_trainRetinanet_R_101_FPN_3x_2000ims_lr0.0005.pth
    threshold: 0.9
    testing_device: cuda  # use cpu or cuda
    saving_predicted_ims: Yes
    show_predicted_ims: No


