
workflow:
  dataset_creation: Yes
  dnn_training: Yes
  dnn_evaluation: Yes
# ---------------------------------
dataset_creation_settings: !include dataset_creation.yaml
# -----------------------------------
dnn_training_settings: !include method_maskRCNN.yaml
# -----------------------------------
dirs_and_files: !include dirs_and_files.yaml
# EOF