dataset:
    name: coco_tree
    hard_negative_background_preparation:
        option: No
        input_dir: datasets/coco_tree/hard_negatives
        output_dir: datasets/coco_tree/backgrounds
        output_width: 1982
        output_height: 1218
        output_type: png
        position: middle_bottom  # position can be: "middle_bottom"
    training_images_preparation:
        option: Yes
        name: coco_tree_train
        input_dir: datasets/coco_tree_experiment  # the dir that contains /foregrounds and /backgrounds dirs
        output_dir: datasets/coco_tree_experiment/training_one_im
        num_images: 1  # number of output images
        max_foregrounds: 15  # maximum number of foreground objects on an image
        output_width: 512
        output_height: 512
        output_type: png
        description: synthesized tree dataset (training)
        url: none
        version: train_2.0
        contributor: DK
        license_name: free
        license_url: none
    validation_images_preparation:
        option: No
        labelme_annotating: Yes  # annotate the ground truth manually
        val_images_dir: datasets/coco_tree/validation/images
        labelme_annotation_dir: datasets/coco_tree/validation/annotations
        converting_labelme_to_coco: Yes
        coco_json_path: datasets/coco_tree/validation/coco_instances.json
