dataset:
    name: coco_tree
    hard_negative_background_preparation:
        option: No
        input_dir: datasets/coco_tree_tank_woodPile/hard_negatives
        output_dir: datasets/coco_tree_tank_woodPile/backgrounds
        output_width: 1982
        output_height: 1218
        output_type: png
        position: middle_bottom_and_right  # position can be: middle_bottom, random, middle_bottom_and_right
    training_images_preparation:
        option: Yes
        name: experiments
        input_dir: datasets/experiment  # the dir that contains /foregrounds and /backgrounds dirs
        output_dir: datasets/experiment/training
        num_images: 10  # number of output images
        max_foregrounds: 15  # maximum number of foreground objects on an image
        output_width: 512
        output_height: 512
        output_type: png
        description: synthesized tree dataset (training, with tank and wood pile)
        url: none
        version: experiment_1.0
        contributor: DK
        license_name: free
        license_url: none
    validation_images_preparation:
        option: No
        labelme_annotating: Yes  # annotate the ground truth manually
        val_images_dir: datasets/coco_tree/validation/images
        labelme_annotation_dir: datasets/coco_tree/validation/annotations
        converting_labelme_to_coco: Yes
        coco_json_path: datasets/coco_tree/validation/coco_instances.json
