dataset:
    name: coco_like
    hard_negative_background_preparation:
        option: Yes
        input_dir: datasets/hard_negatives
        output_dir: datasets/coco_like/backgrounds
        output_width: 512
        output_height: 512
        output_type: png
    training_images_preparation:
        option: Yes
        input_dir: datasets/coco_like
        output_dir: datasets/coco_like/training
        num_images: 2000
        max_foregrounds: 15
        output_width: 512
        output_height: 512
        output_type: png
        description: synthesized tree dataset (training)
        url: none
        version: train_1.0
        contributor: DK
        license_name: free
        license_url: none
    validation_images_preparation:
        option: Yes
        input_dir: datasets/coco_like
        output_dir: datasets/coco_like/validation
        num_images: 500
        max_foregrounds: 15
        output_width: 512
        output_height: 512
        output_type: png
        description: synthesized tree dataset (validation)
        url: none
        version: val_1.0
        contributor: DK
        license_name: free
        license_url: none
