dataset:
    name: coco_tree
    hard_negative_background_preparation:
        option: No
        input_dir: datasets/hard_negatives
        output_dir: datasets/coco_tree/backgrounds
        output_width: 512
        output_height: 512
        output_type: png
    training_images_preparation:
        option: No
        name: coco_tree_train
        input_dir: datasets/coco_tree
        output_dir: datasets/coco_tree/training_subset
        num_images: 200
        max_foregrounds: 15
        output_width: 512
        output_height: 512
        output_type: png
        description: synthesized tree dataset (training)
        url: none
        version: train_1.0
        contributor: DK
        license_name: free
        license_url: none
    validation_images_preparation:
        option: Yes
        labelme_annotating: No
        val_images_dir: datasets/coco_tree/validation/images
        labelme_annotation_dir: datasets/coco_tree/validation/annotations
        converting_labelme_to_coco: No
        coco_json_path: datasets/coco_tree/validation/coco_instances.json
