reconstruct_3d:
    name: coco_tree_reconstruct_3d
    left_ims_dir: datasets/coco_tree/testing/input_consecutive/left_ims
    right_ims_dir:  datasets/coco_tree/testing/input_consecutive/right_ims
    disparity_maps_dir: datasets/coco_tree/testing/input_consecutive/disparity_maps
    output_dir: datasets/coco_tree/testing/output_3d_consecutive
    stereo_params: datasets/coco_tree/testing/stereoParams.yaml
