defaults:
  - dataset: coco_tree
  - model: mask_rcnn_R_50_FPN_3x
    optional: true
  - dataset_model: ${defaults.0.dataset}_${defaults.1.model}
  - hydra/job_logging: colorlog  # additional logging config
  - hydra/hydra_logging: colorlog  # additional logging config

workflow:
  dataset_creation: Yes
  dnn_method: Yes
  reconstruct_3d: No
  demo: No

