defaults:
  - dataset: coco_tree
  - model: retinanet_R_101_FPN_3x
    optional: true
  - dataset_model: ${defaults.0.dataset}_${defaults.1.model}
  - reconstruct_3d: ${defaults.0.dataset}_reconstruct_3d
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

workflow:
  dataset_creation: No
  reconstruct_3d: No
  dnn_method: Yes